import type { FeatureFlags } from "../types/features";

export const featureFlags = {
  tickets: "active",
  waitlist: "active",
  hotels: "active",
  tables: "active",
  discountCodes: "active",
  groupCheckout: "active",
  scanner: "active",
  directMessages: "future",
  autoTranslate: "future",
  memberRegistration: "active",
  emailVerification: "active",
  profileCompletion: "active",
  events: "active",
  ticketing: "active",
  genderBalance: "active",
  eventWaitlist: "active",
  qrCheckIn: "active",
  stripePayments: "beta",
  paypalPayments: "future",
  hotelAddOns: "active",
  tableBookings: "active",
  drinkPackages: "active",
  fruitPlatters: "active",
  bottleService: "active",
  fastLane: "active",
  birthdayPackages: "active",
  groupBooking: "active",
  splitPayments: "active",
  refunds: "future",
  feed: "active",
  follows: "active",
  comments: "active",
  likes: "beta",
  eventAttendees: "active",
  eventChat: "active",
  directChat: "future",
  scannerAccounts: "active",
  adminDashboard: "active",
  revenueDashboard: "active",
  pushNotifications: "future",
  emailBroadcasts: "beta",
  externalOrganizers: "future",
  promoterSystem: "future",
  appleWallet: "future",
  googleWallet: "future",
  stories: "future",
  businessNetworking: "future",
  dating: "disabled",
  marketplace: "future",
  snapMode: "future",
  pokes: "future",
  musicStickers: "future",
  autoTranslation: "future",
  liveLocation: "future",
  smartFeed: "future",
  messageRequests: "future",
  offlineScanner: "future",
  faceValidation: "future",
  googleAuth: "future",
  appleAuth: "future",
  monitoring: "beta",
  errorTracking: "future",
  loadTesting: "future",
} satisfies FeatureFlags;

export const isFeatureVisible = (state: FeatureFlags[keyof FeatureFlags]): boolean =>
  state === "active" || state === "beta";

export const isFeatureUsable = (state: FeatureFlags[keyof FeatureFlags]): boolean =>
  state === "active" || state === "beta";
