import type { JourneyDefinition } from "../types/product";

export const journeys = [
  {
    key: "newUser",
    labelKey: "journeys.newUser.label",
    steps: [
      { key: "landingPage", labelKey: "journeys.steps.landingPage", requiredRole: "guest" },
      { key: "registration", labelKey: "journeys.steps.registration", requiredRole: "guest" },
      { key: "emailVerification", labelKey: "journeys.steps.emailVerification", requiredRole: "user" },
      { key: "profileCompletion", labelKey: "journeys.steps.profileCompletion", requiredRole: "user" },
      { key: "feed", labelKey: "journeys.steps.feed", requiredRole: "user" },
    ],
  },
  {
    key: "ticketPurchaseAvailableQuota",
    labelKey: "journeys.ticketPurchaseAvailableQuota.label",
    steps: [
      { key: "eventPage", labelKey: "journeys.steps.eventPage" },
      { key: "loginCheck", labelKey: "journeys.steps.loginCheck", requiredRole: "user" },
      { key: "verificationCheck", labelKey: "journeys.steps.verificationCheck", requiredVerificationStatus: "verified" },
      { key: "genderQuotaCheck", labelKey: "journeys.steps.genderQuotaCheck" },
      { key: "ticketReservation15Minutes", labelKey: "journeys.steps.ticketReservation15Minutes" },
      { key: "checkout", labelKey: "journeys.steps.checkout" },
      { key: "paymentSuccess", labelKey: "journeys.steps.paymentSuccess" },
      { key: "qrTicketIssued", labelKey: "journeys.steps.qrTicketIssued" },
      { key: "emailConfirmation", labelKey: "journeys.steps.emailConfirmation" },
      { key: "eventChatUnlocked", labelKey: "journeys.steps.eventChatUnlocked", requiresValidTicket: true },
    ],
  },
  {
    key: "waitlist",
    labelKey: "journeys.waitlist.label",
    steps: [
      { key: "eventPage", labelKey: "journeys.steps.eventPage" },
      { key: "loginCheck", labelKey: "journeys.steps.loginCheck", requiredRole: "user" },
      { key: "verificationCheck", labelKey: "journeys.steps.verificationCheck", requiredVerificationStatus: "verified" },
      { key: "genderQuotaFull", labelKey: "journeys.steps.genderQuotaFull" },
      { key: "genderSpecificWaitlist", labelKey: "journeys.steps.genderSpecificWaitlist" },
      { key: "positionShown", labelKey: "journeys.steps.positionShown" },
      { key: "promotionNotification", labelKey: "journeys.steps.promotionNotification" },
      { key: "purchaseWindow15Minutes", labelKey: "journeys.steps.purchaseWindow15Minutes" },
    ],
  },
  {
    key: "groupBooking",
    labelKey: "journeys.groupBooking.label",
    steps: [
      { key: "groupLeaderSelectsEvent", labelKey: "journeys.steps.groupLeaderSelectsEvent", requiredRole: "user" },
      { key: "selectTicketCategory", labelKey: "journeys.steps.selectTicketCategory" },
      { key: "addMembersByUsernameOrEmail", labelKey: "journeys.steps.addMembersByUsernameOrEmail" },
      { key: "allMembersRegisteredCheck", labelKey: "journeys.steps.allMembersRegisteredCheck" },
      { key: "allMembersVerifiedCheck", labelKey: "journeys.steps.allMembersVerifiedCheck" },
      { key: "genderQuotaForAllCheck", labelKey: "journeys.steps.genderQuotaForAllCheck" },
      { key: "reserveIndividualTickets", labelKey: "journeys.steps.reserveIndividualTickets" },
      { key: "createPaymentSplit", labelKey: "journeys.steps.createPaymentSplit" },
      { key: "issueIndividualQrTickets", labelKey: "journeys.steps.issueIndividualQrTickets" },
    ],
  },
  {
    key: "addonBooking",
    labelKey: "journeys.addonBooking.label",
    steps: [
      { key: "validTicketCheck", labelKey: "journeys.steps.validTicketCheck", requiredRole: "user", requiresValidTicket: true },
      { key: "hotel", labelKey: "journeys.steps.hotel" },
      { key: "table", labelKey: "journeys.steps.table" },
      { key: "drinkPackage", labelKey: "journeys.steps.drinkPackage" },
      { key: "fruitPlatter", labelKey: "journeys.steps.fruitPlatter" },
      { key: "bottleService", labelKey: "journeys.steps.bottleService" },
      { key: "birthdayPackage", labelKey: "journeys.steps.birthdayPackage" },
      { key: "fastLane", labelKey: "journeys.steps.fastLane" },
      { key: "cartReview", labelKey: "journeys.steps.cartReview" },
      { key: "payment", labelKey: "journeys.steps.payment" },
      { key: "confirmation", labelKey: "journeys.steps.confirmation" },
    ],
  },
  {
    key: "entryControl",
    labelKey: "journeys.entryControl.label",
    steps: [
      { key: "scannerOpensScanner", labelKey: "journeys.steps.scannerOpensScanner", requiredRole: "scanner" },
      { key: "selectPermittedEvent", labelKey: "journeys.steps.selectPermittedEvent" },
      { key: "scanQr", labelKey: "journeys.steps.scanQr" },
      { key: "verifyHmac", labelKey: "journeys.steps.verifyHmac" },
      { key: "loadTicket", labelKey: "journeys.steps.loadTicket" },
      { key: "showProfileAndTicketStatus", labelKey: "journeys.steps.showProfileAndTicketStatus" },
      { key: "confirmEntry", labelKey: "journeys.steps.confirmEntry" },
      { key: "markTicketUsed", labelKey: "journeys.steps.markTicketUsed" },
    ],
  },
  {
    key: "admin",
    labelKey: "journeys.admin.label",
    steps: [
      { key: "createEvents", labelKey: "journeys.steps.createEvents", requiredRole: "admin" },
      { key: "configureGenderBalance", labelKey: "journeys.steps.configureGenderBalance" },
      { key: "manageTicketTypes", labelKey: "journeys.steps.manageTicketTypes" },
      { key: "manageAddons", labelKey: "journeys.steps.manageAddons" },
      { key: "manageScannerAccess", labelKey: "journeys.steps.manageScannerAccess" },
      { key: "reviewVerifications", labelKey: "journeys.steps.reviewVerifications" },
      { key: "moderatePosts", labelKey: "journeys.steps.moderatePosts" },
      { key: "viewRevenue", labelKey: "journeys.steps.viewRevenue" },
      { key: "sendBroadcasts", labelKey: "journeys.steps.sendBroadcasts" },
    ],
  },
] as const satisfies readonly JourneyDefinition[];

