import type { RoleDefinition, UserRole } from "../types/roles";

export const roles = [
  {
    role: "guest",
    labelKey: "roles.guest.label",
    descriptionKey: "roles.guest.description",
    permissions: [
      "view_public",
      "view_public_landing",
      "view_event_preview",
      "view_legal_pages",
      "start_login",
      "start_registration",
    ],
  },
  {
    role: "user",
    labelKey: "roles.user.label",
    descriptionKey: "roles.user.description",
    permissions: [
      "view_public",
      "view_app",
      "buy_ticket",
      "book_addon",
      "use_chat",
      "view_public_landing",
      "view_event_preview",
      "view_legal_pages",
      "view_feed",
      "create_post",
      "view_profiles",
      "follow_users",
      "view_events",
      "buy_tickets",
      "book_addons",
      "use_event_chat",
    ],
  },
  {
    role: "scanner",
    labelKey: "roles.scanner.label",
    descriptionKey: "roles.scanner.description",
    permissions: [
      "view_public",
      "scan_ticket",
      "view_public_landing",
      "view_event_preview",
      "view_legal_pages",
      "scan_tickets",
      "select_scanner_event",
      "view_scan_result",
      "mark_ticket_used",
    ],
  },
  {
    role: "admin",
    labelKey: "roles.admin.label",
    descriptionKey: "roles.admin.description",
    permissions: [
      "view_public",
      "view_app",
      "buy_ticket",
      "book_addon",
      "use_chat",
      "scan_ticket",
      "manage_orders",
      "manage_discount_codes",
      "manage_scanners",
      "moderate_content",
      "view_admin",
      "view_public_landing",
      "view_event_preview",
      "view_legal_pages",
      "view_feed",
      "create_post",
      "view_profiles",
      "follow_users",
      "view_events",
      "buy_tickets",
      "book_addons",
      "use_event_chat",
      "scan_tickets",
      "select_scanner_event",
      "view_scan_result",
      "mark_ticket_used",
      "create_events",
      "manage_events",
      "manage_users",
      "manage_tickets",
      "manage_addons",
      "manage_hotels",
      "manage_scanner_access",
      "manage_discount_codes",
      "moderate_posts",
      "view_bookings",
      "view_revenue",
      "send_broadcasts",
    ],
  },
] as const satisfies readonly RoleDefinition[];

export const getRoleDefinition = (role: UserRole): RoleDefinition =>
  roles.find((definition) => definition.role === role) ?? roles[0];

export const roleHasPermission = (role: UserRole, permission: RoleDefinition["permissions"][number]): boolean =>
  getRoleDefinition(role).permissions.includes(permission);
